


name: FullTest

on: push

jobs:

  build-test:

    name: sml code base
    runs-on: macos-latest
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Install SML (macos)
        run: |
          config/install.sh
          export PATH="/Users/runner/work/legacy/legacy/bin::$PATH"
      
      - name: Recompile (macos)
        run: |    
          cd base/system
          cmb-make ../../bin/sml
          makeml 
          installml -clean
      - name: Re-Install SML (macos)
        run: |
          config/install.sh
          export PATH="/Users/runner/work/legacy/legacy/bin::$PATH"
          
      - name: Create test scripts
        run: |
          cat > test-script <<EOF
          #!/home/jbw/daya-fork-smlnj-legacy/bin/sml --script
          print "Hello!\n";
          EOF
          chmod a+x test-script
          
      - name: Test execution (macos)
        run: |
          ./testscript
