name: FullTest

on: 
    workflow_dispatch:

jobs:

  build-test:

    name: sml code base
    runs-on: macos-latest
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Install SML (macos)
        run: |
          config/install.sh
      
      - name: Recompile (macos)
        run: |    
          cd base/system
          ./cmb-make /Users/runner/work/legacy/legacy/bin/sml
          ./makeml 
          ./installml -clean
          
      - name: Re-Install SML (macos)
        run: |
          config/install.sh
                    
      - name: Create test scripts
        run: |
          cat > test-script <<EOF
          #!/usr/bin/env -Ssml --script
          print "Hello!\n";
          EOF
          chmod a+x test-script
          
      - name: Test execution (macos)
        run: |
          export PATH="/Users/runner/work/legacy/legacy/bin::$PATH"
          ./testscript
