name: installonly

on: 
    workflow_dispatch:

jobs:

  build-test:

    name: sml code base
    runs-on: macos-latest
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Install SML (macos)
        run: |
          config/install.sh
          
      - name: Test execution (macos)
        run: |
          export PATH="/Users/runner/work/legacy/legacy/bin::$PATH"
          sml
