 

name: testsml

on: push

jobs:

  build-test:

    name: sml code base
    runs-on: macos-latest
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Install SML (macos)
        run: |
          config/install.sh
          export PATH="/Users/runner/work/legacy/legacy/bin::$PATH"
          
      - name: Create test file
        run: |
          cat > test-script.sml <<EOF
          print "Hello DAYA!\n";
          EOF

      - name: Test execution (macos)
        run: |
          sml test-script.sml
